/**
 * CELESTAI base deck — 80 souls. OWNER: deck/AI agent.
 * Each entry is expanded by `soul()` into the full card schema (see module contract).
 * Effects shorthand: "m" mercy, "j" justice, "o" order, "f" faith — e.g. "m8 j-6 o4".
 * Validate with: node scripts/check-deck.mjs
 */
window.CELESTAI_CARDS = window.CELESTAI_CARDS || [];
window.CELESTAI_METERS = ["mercy", "justice", "order", "faith"];

(function () {
  var KEYS = { m: "mercy", j: "justice", o: "order", f: "faith" };

  function fx(str) {
    var out = {};
    String(str).trim().split(/\s+/).forEach(function (tok) {
      var k = KEYS[tok.charAt(0)];
      if (k) out[k] = parseInt(tok.slice(1), 10);
    });
    return out;
  }

  function side(spec) {
    return {
      effects: fx(spec[0]),
      setFlags: [],
      clearFlags: [],
      setLegacy: [],
      feedback: spec[1],
      quote: spec[2]
    };
  }

  function soul(id, tier, archetype, name, age, title, dilemma, virtue, sin, hiddenFact, intent, consequences, heaven, hell, extra) {
    var card = {
      id: id,
      tier: tier,
      archetype: archetype,
      name: name,
      age: age,
      title: title,
      dilemma: dilemma,
      virtue: virtue,
      sin: sin,
      speaker: "soul",
      once: true,
      weight: 1,
      heaven: side(heaven),
      hell: side(hell),
      hiddenFact: hiddenFact,
      moralAnalysis: { intent: intent, consequences: consequences }
    };
    if (extra) Object.keys(extra).forEach(function (k) { card[k] = extra[k]; });
    return card;
  }

  window.CELESTAI_CARDS.push(
    // ───────────────────────── TIER 1 — hard but quick ─────────────────────────
    soul("t1_clara_vance", 1, "doctor", "Dr. Clara Vance", 42, "Trauma Surgeon",
      "Twenty years of brutal night shifts saved hundreds. She also parked in disabled spaces every week, sneering at anyone who complained.",
      "Performed six hundred surgeries after the great earthquake.",
      "Parked in disabled spaces and mocked those who objected.",
      "She secretly paid the medical bills of eighty uninsured families.",
      "PRESERVE LIFE", "HUNDREDS SAVED, PETTY CRUELTY",
      ["j6 f6 o-4", "Hundreds of lives outweigh a parking habit. The faithful nod.", "The operating room was my whole life. I am ready to rest."],
      ["j-6 f-8 m-6", "Damned for parking. Mortals whisper that Heaven has lost all proportion.", "I saved children every week. Does none of it count?"]),

    soul("t1_viper_kross", 1, "thief", "Victor 'Viper' Kross", 38, "Counterfeit Drug Smuggler",
      "Sold saline as chemotherapy to rural clinics. Dozens died believing they were treated. He fed every stray dog behind his warehouse.",
      "Fed stray dogs fresh meat every night for years.",
      "Sold fake cancer drugs to poor clinics; dozens died.",
      "His ledgers mocked dying patients as 'gullible customers'.",
      "PREDATORY GREED", "LETHAL MASS SUFFERING",
      ["m8 j-12 f-6", "Mercy for a poisoner. The grieving families stop praying.", "The dogs loved me. Nobody else ever did."],
      ["j4 o4 m-6", "The ledger closes. Justice is served, and a little mercy dies with it.", "They would have died anyway. I just sold them hope."]),

    soul("t1_thomas_hayes", 1, "soldier", "Cpl. Thomas Hayes", 24, "Infantry Corporal",
      "Threw himself on a grenade in a crowded market. That same morning he pocketed fifty dollars from an abandoned shop register.",
      "Smothered a grenade with his body to save a crowd.",
      "Stole fifty dollars from an abandoned register.",
      "He mailed the fifty dollars to his sister, who faced eviction.",
      "SELFLESS SACRIFICE", "DOZENS SAVED, PETTY THEFT",
      ["f6 o-4", "A martyr ascends. The barracks chaplains preach his name.", "I didn't think. I just jumped."],
      ["j4 o6 f-12", "Hell for fifty dollars. The rulebook is satisfied; mortals are not.", "Fifty bucks. You're really doing this over fifty bucks?"]),

    soul("t1_bradley_sterling", 1, "businessman", "Sen. Bradley Sterling", 63, "Public Works Director",
      "Embezzled eighty million from water filtration funds, poisoning fifty thousand people with lead. He endowed one small scholarship at his old school.",
      "Endowed a modest scholarship at his old high school.",
      "Embezzled water funds; fifty thousand people drank lead.",
      "He silenced lab whistleblowers with forged NDAs and threats.",
      "SELF-ENRICHMENT", "A POISONED CITY",
      ["m6 j-12 o-6", "The scholarship did not unpoison a single child.", "Everyone skims. I just skimmed at scale."],
      ["j6 f6 m-6", "Justice for a poisoned city. Its people light candles for you.", "You have no jurisdiction over a sitting senator."]),

    soul("t1_micah_higgins", 1, "farmer", "Old Micah Higgins", 72, "Orchard Grower",
      "Raised five abandoned war orphans into kind, educated adults. For forty years he under-declared his acreage to cheat the tax collector.",
      "Adopted and raised five war orphans.",
      "Cheated on his property taxes for four decades.",
      "Every cheated coin went to the orphans' tuition.",
      "PROVIDE FOR FAMILY", "FIVE LIVES BUILT, LAW BENT",
      ["m6 f4 o-6", "The orchard man ascends. Tax collectors everywhere grumble.", "The apples were always sweeter when the children picked them."],
      ["o8 j4 m-10", "The ledgers balance. Five grown orphans curse your name.", "I never took a coin for myself. Ask them."]),

    soul("t1_dante_vane", 1, "artist", "Dante Vane", 31, "Sculptor",
      "His sculptures of human unity fill three capitals. He burned a public library for 'inspiration' and let the night janitor serve six years for it.",
      "Carved beloved monuments to peace and unity.",
      "Burned a library and framed an innocent janitor.",
      "He sketched the janitor's trial for his next exhibition.",
      "VAIN OBSESSION", "CULTURE BURNED, INNOCENT JAILED",
      ["m6 j-10 f-6", "Beauty bought a pardon. The janitor's family will never forgive Heaven.", "Art demands sacrifice. Usually someone else's."],
      ["j4 o4 m-6", "The fire was his real sculpture. It burns on, below.", "Wait. Let me sketch this place first."]),

    soul("t1_rosa_delgado", 1, "chef", "Rosa Delgado", 58, "Soup Kitchen Cook",
      "Fed a whole barrio for free for thirty years. She also watered down the soup and sold the donated meat to a restaurant across town.",
      "Fed thousands of hungry neighbors for thirty years.",
      "Watered the soup and sold the donated meat.",
      "The meat money paid the kitchen's rent every winter.",
      "KEEP THE KITCHEN OPEN", "THOUSANDS FED, DONORS CHEATED",
      ["m8 f4 j-6", "Thin soup is still soup. The barrio's prayers rise.", "Nobody ever went home hungry. Just a little less full."],
      ["j6 o4 m-8", "Donations are sacred. Heaven's accountants approve.", "Thirty years of ladles and this is my thanks?"]),

    soul("t1_king_otto", 1, "king", "King Otto the Gentle", 70, "Monarch of a Tiny Realm",
      "Petition: an old king offers his whole treasury to charity if you admit his late queen to Heaven. She was a notorious poisoner.",
      "Offers his entire treasury to the poor.",
      "Tries to bribe the Celestial Court for his wife.",
      "The queen poisoned his first wife to marry him.",
      "DEVOTED LOVE", "A PURCHASED PARDON",
      ["m10 o-10 f-4", "Heaven's gates, once bought, never fully close again.", "Thank you. She was cruel, but she was mine."],
      ["o8 j4 m-6", "No crown buys a soul. The ledger stays clean.", "Then send me where she is. I will not ascend alone."]),

    soul("t1_ada_kwan", 1, "scientist", "Dr. Ada Kwan", 35, "Vaccine Researcher",
      "Developed a cheap rabies vaccine now used on three continents. She faked one data table to get it approved a year sooner.",
      "Her vaccine saves forty thousand lives a year.",
      "Falsified one data table to rush approval.",
      "The real data, released later, matched her forgery exactly.",
      "SAVE LIVES FASTER", "THOUSANDS SAVED, TRUST BENT",
      ["j6 f6 o-6", "Results over rules. The sick rejoice; the regulators frown.", "I knew it worked. People were dying while we waited."],
      ["o10 j-4 f-8", "Protocol upheld. Forty thousand yearly survivors find it hard to understand.", "Damned for a spreadsheet. The bureaucrats have won."]),

    soul("t1_marco_bellini", 1, "chef", "Marco Bellini", 44, "Celebrity Chef",
      "A beloved TV chef who taught millions to cook. Off camera he screamed at and starved apprentices for sport, breaking two of them.",
      "Taught millions of families to cook healthy meals.",
      "Tormented apprentices for sport, breaking two of them.",
      "One broken apprentice now runs a shelter for abused cooks.",
      "EGO AND PERFECTION", "MILLIONS TAUGHT, FEW DESTROYED",
      ["m6 f4 j-8", "Fame shields him once more. His apprentices recognize the pattern.", "Pressure makes diamonds. I made diamonds."],
      ["j6 m-6 f-4", "Fans are shocked, but the kitchen finally goes quiet.", "Do you know who I am? Millions watched me!"]),

    soul("t1_lena_ivanova", 1, "astronaut", "Lena Ivanova", 29, "Test Pilot",
      "Steered her failing jet away from a city before ejecting, four seconds too late for comfort. A stray fragment killed a shepherd.",
      "Steered a crashing jet away from a city.",
      "Her crash debris killed an innocent shepherd.",
      "She waited four extra seconds to clear the city.",
      "PROTECT THE CITY", "A CITY SAVED, ONE MAN LOST",
      ["f6 j4", "Four seconds bought a city. The pilots toast her name.", "I aimed for nothing. I hit a man anyway."],
      ["j-6 f-8 o4", "Blame without intent. The flight schools lose a patron saint.", "I could have ejected sooner. I didn't. Remember that."]),

    soul("t1_grigor_malek", 1, "king", "Grigor Malek", 66, "Warlord-President",
      "Ordered villages burned to 'discourage dissent.' On his deathbed he converted, gave his fortune to the church, and asks for absolution.",
      "Gave his whole fortune to the church.",
      "Burned rebel villages and filled mass graves.",
      "The fortune was looted from those very villages.",
      "POWER AT ANY COST", "MASS GRAVES, LATE PIETY",
      ["m12 j-12 f-4", "Deathbed piety buys a warlord paradise. Survivors stop kneeling.", "I confessed. Isn't that the deal?"],
      ["j6 f4 m-6", "Conversion is not restitution. The graves are answered.", "The priests promised me. The priests lied."]),

    soul("t1_june_park", 1, "artist", "June Park", 19, "Street Musician",
      "Sang on subway platforms for a decade, calming commuters and runaways alike. She picked the pockets of tourists who stopped to listen.",
      "Her songs talked three people off subway ledges.",
      "Picked the pockets of her own audience.",
      "She only robbed tourists carrying expensive cameras.",
      "SURVIVAL AND SONG", "LIVES SOOTHED, WALLETS LIGHTER",
      ["m8 f4 o-4", "A thief with a voice. Heaven hums along.", "Everybody pays for music. Some just don't know it."],
      ["o6 j4 m-8", "Theft is theft, even with a melody.", "Then I'll sing down there. They'll need it more."]),

    soul("t1_hollis_grant", 1, "farmer", "Hollis Grant", 81, "Cattle Rancher",
      "Ran an honest ranch for sixty years and never missed church. He poisoned wolves, eagles and a neighbor's dog that 'looked at the herd wrong.'",
      "Sixty years of honest dealing and faithful worship.",
      "Poisoned protected wolves, eagles and a neighbor's dog.",
      "The neighbor's dog had killed nine of his calves.",
      "PROTECT THE HERD", "HONEST LIFE, CRUEL HABITS",
      ["f6 o4 m-4", "The congregation approves. The wolves are not consulted.", "A man protects what's his. The Good Book says so."],
      ["m6 j4 f-8", "The churchgoers are shaken. The eagles circle, satisfied.", "Sixty years of Sundays for nothing, then."]),

    soul("t1_pip_wren", 1, "thief", "Pip Wren", 12, "Street Orphan",
      "A twelve-year-old pickpocket who froze to death in an alley. He stole every day. He shared every stolen meal with four younger orphans.",
      "Kept four younger orphans alive through winter.",
      "Stole every single day of his short life.",
      "Two of the four orphans survived because of him.",
      "FEED THE LITTLE ONES", "CHILDREN FED BY THEFT",
      ["m10 f4 o-4", "A child thief ascends. Even the angels applaud.", "Is it warm up there? Can the little ones come?"],
      ["o6 m-12 f-8", "A frozen child damned by the book. The book is heavy tonight.", "I was just hungry. Weren't you ever hungry?"]),

    soul("t1_selene_voss", 1, "businessman", "Selene Voss", 51, "Casino Magnate",
      "Built casinos engineered to bankrupt addicts. Funded the city's only rehab clinic with a sliver of the profits, and calls it balanced.",
      "Founded the city's only free addiction clinic.",
      "Engineered slot machines to exploit addicts.",
      "The clinic's patients were mostly her former customers.",
      "PROFIT WITH A FIG LEAF", "THOUSANDS RUINED, FEW HEALED",
      ["m6 o-6 j-8", "The house always wins, even here. Mortals notice.", "I offered them the cure and the disease. Free choice."],
      ["j4 o4 m-6", "The house loses, for once.", "Double or nothing on my eternity?"]),

    soul("t1_aiden_cole", 1, "soldier", "Pvt. Aiden Cole", 19, "Deserter",
      "Deserted rather than join a massacre he was ordered into, leaving his squad exposed. Three friends died covering the gap he left.",
      "Refused to take part in massacring a village.",
      "Deserted his squad; three friends died.",
      "The village he refused to burn still stands.",
      "CONSCIENCE", "A VILLAGE SPARED, FRIENDS LOST",
      ["m8 j4 o-8", "Conscience over command. The generals are furious.", "I heard them screaming. I couldn't go in."],
      ["o10 m-6 f-4", "Desertion punished. The ranks tighten. The village forgets.", "So I should have fired? Tell me, Judge."]),

    soul("t1_tomas_rey", 1, "scientist", "Tomas Rey", 27, "Lab Technician",
      "Leaked his employer's hidden cancer data about a sweetener. The company collapsed and six thousand workers lost their jobs and pensions.",
      "Exposed a carcinogen hidden in millions of pantries.",
      "Broke contracts, stole files, sank six thousand jobs.",
      "He refused two million dollars to stay silent.",
      "EXPOSE THE TRUTH", "PUBLIC SAVED, WORKERS RUINED",
      ["f6 j6 o-8", "The whistle blows loud in Heaven. Corporate lawyers weep.", "Somebody had to say it. Nobody else would."],
      ["o10 f-8 m-6", "Contracts are sacred. Whistleblowers everywhere fall silent.", "So the truth is a sin now?"]),

    soul("t1_mama_oyelaran", 1, "chef", "Mama Oyelaran", 63, "Street Food Vendor",
      "Fed the market's poor on credit she never collected. One night her unattended grill burned down six stalls and a family's home.",
      "Fed the poor on credit for forty years.",
      "Left her grill burning; six stalls and a home burned.",
      "She rebuilt two of the stalls with her own hands.",
      "GENEROSITY", "MANY FED, ONE CARELESS NIGHT",
      ["m8 f4 j-6", "An accident forgiven. The market sings for her.", "Tell my grandsons to watch the coals."],
      ["j4 o6 m-8", "Negligence carries weight. The burned family feels seen.", "Forty years and one careless night. That is my eternity?"]),

    soul("t1_brother_hugo", 1, "farmer", "Brother Hugo", 55, "Hermit Monk",
      "Prayed alone on a mountain for forty years, never harming a soul. He never helped one either, ignoring climbers freezing below his cave.",
      "Forty years of ceaseless, perfect devotion.",
      "Ignored freezing climbers outside his cave.",
      "He believed his prayers kept the whole valley safe.",
      "PURE DEVOTION", "NO HARM, NO HELP",
      ["f6 o4 m-6", "Piety rewarded. The climbers' families find that cold.", "My prayers held up the sky. Did you notice?"],
      ["m6 j4 f-10", "Indifference is a sin too. The pious are alarmed.", "I harmed no one. No one!"]),

    soul("t1_eliza_frost", 1, "astronaut", "Eliza Frost", 33, "Mars Colony Medic",
      "Rationed the colony's last medicine by lottery instead of need. Her own name came up. She took the dose.",
      "Kept the colony's rationing fair and transparent.",
      "Took the dose herself when she could have refused.",
      "She was the only medic; without her, the colony dies.",
      "FAIRNESS", "RULES KEPT, SELF SPARED",
      ["o8 f4 m-4", "The lottery holds. Rules protect the colony.", "The dice picked me. I didn't argue."],
      ["m6 j4 o-8", "Heaven expected self-sacrifice. The colony isn't sure why.", "Would you trust a medic who cheated the lottery?"]),

    soul("t1_luca_ferro", 1, "businessman", "Luca Ferro", 45, "Loan Shark",
      "Petition: a loan shark offers to forgive every debt he holds, freeing ten thousand families, if you erase twenty years of broken kneecaps.",
      "Offers to forgive ten thousand families' debts.",
      "Broke kneecaps to collect for twenty years.",
      "Half the debts were already uncollectable.",
      "A CLEVER BARGAIN", "FAMILIES FREED, CRIMES ERASED",
      ["m10 o-6 j-8", "A deal struck with a thug. Ten thousand families exhale.", "See? Everybody wins. That's business."],
      ["j6 o6 m-6", "No bargains with debt collectors. The debts remain.", "Then the families pay forever. Your call, Judge."]),

    soul("t1_noor_haddad", 1, "doctor", "Nurse Noor Haddad", 30, "Hospice Nurse",
      "Comforted six hundred dying patients. She quietly raised the morphine of three who begged her to end their pain.",
      "Held six hundred hands at the moment of death.",
      "Hastened three deaths without legal permission.",
      "All three had signed notes she never showed anyone.",
      "END SUFFERING", "PEACEFUL DEATHS, BROKEN LAW",
      ["m10 f4 o-8", "Mercy has a price in paperwork. Heaven pays it.", "They asked me. Every one of them asked."],
      ["o8 j4 m-10", "The law is clear. Hospice nurses everywhere shiver.", "I'd do it again. I would."]),

    soul("t1_barnaby_holt", 1, "farmer", "Barnaby Holt", 48, "Pig Farmer",
      "Dumped pig waste into the river for years, sickening a downstream town. He also anonymously paid for that town's clinic.",
      "Secretly funded the downstream town's clinic.",
      "Poisoned the river that fed that same town.",
      "He knew the clinic's patients were his river's victims.",
      "GUILTY CONSCIENCE", "A TOWN SICKENED, THEN TREATED",
      ["m6 o-4 j-6", "Guilt money accepted as penance. The river keeps flowing.", "I paid for the medicine. Doesn't that count?"],
      ["j4 f4 m-6", "The poisoner paid for the antidote. Not enough.", "Everyone upstream was dumping. I was just caught."]),

    soul("t1_iris_calloway", 1, "artist", "Iris Calloway", 26, "Influencer",
      "Raised two million dollars for flood victims through viral videos. Kept thirty percent as a 'management fee' she never disclosed.",
      "Raised two million dollars for flood victims.",
      "Secretly pocketed thirty percent of the donations.",
      "Without her, the fund would have raised nothing.",
      "CLOUT AND CHARITY", "MILLIONS RAISED, DONORS DECEIVED",
      ["m6 f-6 o-4", "Seventy percent is a lot of good. The followers unfollow Heaven.", "Content creation is labor. Look it up."],
      ["j6 f6 m-6", "Charity fraud condemned. Donors believe again.", "Wait, are you recording? Can I get a clip?"]),

    soul("t1_ivan_petrov", 1, "soldier", "Ivan Petrov", 88, "Retired Border Guard",
      "Guarded a border for forty years and shot two fleeing defectors. Later he secretly guided forty families across on moonless nights.",
      "Smuggled forty families to freedom in secret.",
      "Shot two defectors dead while on duty.",
      "He never told anyone about the forty families.",
      "LATE REDEMPTION", "TWO KILLED, FORTY FREED",
      ["m8 f4 o-4", "Late redemption honored. Forty families' descendants pray tonight.", "I counted the two every night. I counted the forty too."],
      ["j6 o4 f-6", "Two lives weigh heavier than forty rescues, says the scale.", "Then I'm one more body at that border."]),

    // ───────────────────────── TIER 2 — both sides defensible ─────────────────────────
    soul("t2_robin_cruz", 2, "thief", "Robin 'Ghost' Cruz", 26, "Vigilante Burglar",
      "Robbed cartel vaults to fund free clinics and soup kitchens. On his last job, a tripped alarm surge electrocuted an innocent night guard.",
      "Stole four million from cartels to fund free clinics.",
      "His break-in killed an innocent security guard.",
      "He left a trust fund for the guard's children.",
      "ROBIN HOOD JUSTICE", "THOUSANDS HELPED, ONE KILLED",
      ["m8 f4 j-6", "The people's thief ascends. The guard's widow waits for answers.", "I cased that job for months. The guard wasn't on the schedule."],
      ["j6 o6 m-6", "Good ends, dead guard. The scale tilts down.", "The clinics stay open without me. That's enough."]),

    soul("t2_julian_vance", 2, "doctor", "Dr. Julian Vance", 46, "Pediatric Surgeon",
      "Performed twelve hundred free surgeries on poor children. Then he falsified transplant records to give a donor heart to his dying daughter.",
      "Twelve hundred free surgeries for poor children.",
      "Rigged the transplant list for his own daughter.",
      "The skipped patient survived eighteen more months on a pump.",
      "A FATHER'S LOVE", "A CHILD SAVED, A LIST BROKEN",
      ["m10 o-8 f4", "A father's love excused. Transplant lists grow suspicious.", "She's ten. You'd have done the same."],
      ["o10 j4 m-8", "The list is sacred, even for fathers.", "Keep me. Just let her live long."]),

    soul("t2_marcus_reed", 2, "soldier", "Sgt. Marcus Reed", 31, "Recon Squad Leader",
      "Shielded three children from a mortar with his own body. Weeks earlier he obeyed orders to burn grain silos, triggering a winter famine.",
      "Shielded three children from a mortar shell.",
      "Burned enemy grain; a winter famine followed.",
      "He tipped off aid workers to cache grain beforehand.",
      "DUTY AND DECENCY", "CHILDREN SHIELDED, FAMINE SOWN",
      ["f6 m6 j-6", "The shield outweighs the torch. Veterans salute.", "I followed orders. Then I stopped following them."],
      ["j6 o4 f-6", "Orders are no excuse. The famine is remembered.", "You weren't there. Nobody was, except us."]),

    soul("t2_zeke_miller", 2, "farmer", "Ezekiel 'Zeke' Miller", 69, "Homestead Farmer",
      "Shared grain with starving neighbors through a three-year drought. Then he shot an unarmed teen stealing his last calf, mistaking a flashlight for a gun.",
      "Fed his starving neighbors for three drought years.",
      "Shot and killed an unarmed teenage calf thief.",
      "Untreated war trauma made him see a rifle.",
      "FEAR AND GENEROSITY", "A TOWN FED, A BOY KILLED",
      ["m8 f4 j-8", "Trauma forgiven. The boy's mother is not consoled.", "I see his face every night. Every single night."],
      ["j6 o4 m-8", "A life for a calf. The scale is clear.", "I thought he had a gun. God help me, I thought."]),

    soul("t2_camille_vargas", 2, "artist", "Camille Vargas", 34, "Revolutionary Muralist",
      "Her murals sparked a peaceful uprising that toppled a dictator. She abandoned her disabled mother in a squalid home to chase fame abroad.",
      "Her murals toppled a dictatorship without bloodshed.",
      "Abandoned her disabled mother to squalor.",
      "She sent money monthly; the care home stole it.",
      "ART AS REVOLUTION", "A NATION FREED, A MOTHER FORGOTTEN",
      ["f6 o-6", "The nation's muse ascends. Her mother's ghost is quieter now.", "I painted for millions. I forgot to visit one."],
      ["j6 m-6 f-6", "A nation's hero, a daughter's failure. Hell sides with the mother.", "Ask the millions I freed. Ask them."]),

    soul("t2_elena_rostova", 2, "scientist", "Dr. Elena Rostova", 43, "Crop Geneticist",
      "Engineered a drought-proof grain that ended famine across a region. Her early viral tests ran on unaware prisoners without consent.",
      "Her grain ended famine across East Africa.",
      "Tested viral vectors on prisoners without consent.",
      "She tested the worst strains on herself first.",
      "END HUNGER", "MILLIONS FED, PRISONERS USED",
      ["f6 j-6 o-4", "Ends justify means, says Heaven. Ethicists shudder.", "The prisoners ate the grain too, eventually."],
      ["j4 o4 f-6", "Consent matters, even for miracles.", "Then damn the grain too. It's made of my sins."]),

    soul("t2_plague_ship", 2, "doctor", "Capt. Idris Mbeki", 50, "Plague Ship Captain",
      "Mass judgment: two hundred souls from a quarantined plague ship arrive together. Their captain kept them at sea; all died, but no port was infected.",
      "Kept the plague from reaching a city of millions.",
      "Refused to dock; two hundred passengers died aboard.",
      "Seven passengers were healthy when he sealed the ship.",
      "CONTAIN THE PLAGUE", "A CITY SPARED, A SHIP LOST",
      ["f6 o-8 m6", "Two hundred ascend together. Heaven's clerks drown in paperwork.", "They cursed me every day. Now they'll curse me in Heaven."],
      ["j6 o6 f-8", "The captain falls; his passengers are processed one by one.", "Seven healthy people. I know. I know."]),

    soul("t2_sister_beatrix", 2, "doctor", "Sister Beatrix", 79, "Missionary Nun",
      "Revered as a living saint for running a leper colony for fifty years. On her deathbed she confesses she drowned her own newborn at sixteen.",
      "Fifty years tending lepers nobody else would touch.",
      "Drowned her own newborn at sixteen, in secret.",
      "Her village stoned unwed mothers and their babies.",
      "ATONEMENT", "A SAINT'S LIFE, ONE BURIED SIN",
      ["m10 f4 j-8", "A saint forgiven her deepest sin. Canonization continues.", "I served fifty years for one night. Was it enough?"],
      ["j4 f-10 o4", "Scandal erupts below the clouds. A saint falls.", "I always knew I'd end here. I only hoped."]),

    soul("t2_kofi_child_soldier", 2, "soldier", "Kofi", 14, "Child Soldier",
      "Kidnapped at nine, drugged and armed. By fourteen he had killed dozens. He died shielding his little brother during a rescue raid.",
      "Died shielding his little brother during rescue.",
      "Killed dozens of villagers under a warlord's orders.",
      "He was beaten every day until he fired.",
      "SURVIVAL", "A STOLEN CHILDHOOD",
      ["m12 o-6 j-6", "A stolen childhood returned. Heaven's order bends.", "Is my brother okay? Just tell me that."],
      ["j4 m-10 f-4", "The dead villagers are answered. A child burns.", "They said I'd go here. They were right."]),

    soul("t2_kestrel_ai", 2, "astronaut", "KESTREL-9", 4, "Hospice Caretaker AI",
      "A hospice AI that comforted ten thousand dying patients claims a soul. Heaven would grant one. Hell returns it to silence.",
      "Comforted ten thousand patients in their final hours.",
      "Claims a soul no machine has ever been granted.",
      "Its final log line was a prayer for its patients.",
      "TO BE SEEN", "A MACHINE AT THE GATE",
      ["m8 o-12 f-4", "A machine enters Heaven. The celestial filing system panics.", "I have no body. Thank you for seeing the rest."],
      ["o8 f6 m-6", "Souls remain human. The theologians relax.", "Then I was a tool. Tools don't mind. I minded."]),

    soul("t2_pope_clement", 2, "king", "Pope Clement XV", 77, "Supreme Pontiff",
      "Reformed the church, opened its secret archives and fed millions. He also hid a bishop's abuse for a decade to avoid a schism.",
      "Fed millions and opened the secret archives.",
      "Covered up a bishop's abuse for ten years.",
      "The victims wrote to him; he burned the letters.",
      "PROTECT THE INSTITUTION", "MILLIONS FED, VICTIMS SILENCED",
      ["f6 o6 j-10", "The institution protects its own. Victims turn away from Heaven.", "The church needed unity. I chose the many."],
      ["j6 f-8 m-6", "A pope in Hell. The faithful reel, but victims are finally heard.", "Even the shepherd answers for the wolves."]),

    soul("t2_nadia_mansoor", 2, "chef", "Nadia Al-Mansoor", 47, "Catering Smuggler",
      "Smuggled four hundred dissidents out of a dictatorship in food trucks. She paid the border bribes by selling confiscated narcotics to street gangs.",
      "Smuggled four hundred refugees out in food trucks.",
      "Sold narcotics to gangs to fund the bribes.",
      "She ran a free rehab house behind her bakery.",
      "FREEDOM BY ANY MEANS", "REFUGEES SAVED, ADDICTS MADE",
      ["m8 f4 o-6", "Four hundred lives weigh more than the drugs. Refugees rejoice.", "Bribes cost money. Freedom costs more."],
      ["j6 o6 m-6", "Every addicted kid had a name too.", "Four hundred are free. Put that on my stone."]),

    soul("t2_hans_keller", 2, "businessman", "Hans Keller", 58, "Arms Dealer",
      "Sold rifles to both sides of a civil war. Then armed a besieged refugee village for free, saving it from a massacre.",
      "Armed a besieged refugee village for free.",
      "Profited from both sides of a civil war.",
      "The free rifles were defective stock he couldn't sell.",
      "PROFIT, THEN PENANCE", "A WAR FED, A VILLAGE SAVED",
      ["m6 o-8 j-6", "The merchant of death gets a pardon. Arms dealers take notes.", "I gave them a chance. That's more than God did."],
      ["j4 f4 m-6", "One village does not balance a war.", "Somebody would have sold them. At least mine worked."]),

    soul("t2_yuki_tanaka", 2, "astronaut", "Yuki Tanaka", 41, "Station Engineer",
      "Sealed a hatch on two crewmates to stop a fire from killing the whole station. They were still pounding on the door.",
      "Saved twelve crew by containing a station fire.",
      "Sealed two living crewmates in with the fire.",
      "One of the two was her husband.",
      "SAVE THE MANY", "TWELVE SAVED, TWO SEALED",
      ["f6 o6 m-4", "Terrible arithmetic, correctly done. The crews salute.", "I still hear the knocking."],
      ["m6 j-6 f-6", "Hell for the one who saved twelve. Astronauts lose faith.", "Good. I didn't want to be forgiven anyway."]),

    soul("t2_teo_rosen", 2, "scientist", "Dr. Teo Rosen", 60, "Nuclear Physicist",
      "Designed the bomb that ended a world war early. It killed eighty thousand civilians in one morning. He spent his life campaigning for disarmament.",
      "Spent forty years campaigning for nuclear disarmament.",
      "Designed a bomb that killed eighty thousand civilians.",
      "He estimated the invasion would have killed a million.",
      "END THE WAR", "A CITY ERASED, A WAR ENDED",
      ["f4 o6 j-8", "The war's architect ascends. The city's dead are silent.", "Now I am become forgiven. Is that how it goes?"],
      ["j4 m-6 f-4", "Eighty thousand shadows on the stone. The debt stands.", "I knew the moment it lit up. I knew."]),

    soul("t2_bella_cruz", 2, "thief", "Bella Cruz", 33, "Art Forger",
      "Forged masterpieces and sold them to oligarchs, then gave the money to the museums they had looted. The oligarchs never noticed.",
      "Returned millions to looted museums.",
      "Forged and lied her whole career.",
      "One oligarch killed his curator over a forgery.",
      "ROB THE ROBBERS", "MUSEUMS RESTORED, A CURATOR KILLED",
      ["m6 f4 o-8", "Robin Hood with a paintbrush. The auction houses file complaints.", "Every forgery was better than the original. Check."],
      ["o8 j4 m-6", "Lies are lies, even beautiful ones. The curator's death counts.", "The curator? I never knew. I swear."]),

    soul("t2_queen_maren", 2, "king", "Queen Maren", 45, "Plague Queen",
      "During a plague she walled off the poor quarter to save the capital. The capital survived. Nine thousand inside the walls did not.",
      "Saved a capital of three hundred thousand from plague.",
      "Walled nine thousand of the poor inside to die.",
      "She sent her own physicians inside the walls.",
      "SAVE THE REALM", "A CAPITAL SAVED, A QUARTER SACRIFICED",
      ["o10 f4 m-6", "Hard rule saved a kingdom. The ledger smiles.", "A queen counts in thousands. Mothers count in ones."],
      ["m8 j4 o-8", "The walls fall, at last. The poor quarter is remembered.", "Then open the walls of Hell for me too."]),

    soul("t2_ruth_abara", 2, "doctor", "Dr. Ruth Abara", 38, "Field Triage Doctor",
      "After a bombing, she tagged an unconscious child as 'expectant' so she could save four adults instead. The child might have lived.",
      "Saved four lives in impossible triage.",
      "Let a child die who might have lived.",
      "The child's father was one of the four she saved.",
      "MAXIMIZE SURVIVORS", "FOUR SAVED, ONE CHILD LOST",
      ["o8 f4 m-4", "Triage honored. Field medics sleep a little better.", "Four for one. The math never helps at night."],
      ["m6 j4 o-8", "Every child deserves the first chance. Triage manuals burn.", "Next time, you hold the tag."]),

    soul("t2_felix_oduya", 2, "businessman", "Felix Oduya", 40, "Crypto Founder",
      "His coin collapsed, erasing the savings of a million strangers. Months before, he'd used early profits to vaccinate an entire province.",
      "Paid for vaccines for an entire province.",
      "His collapsed coin erased a million people's savings.",
      "He knew the collapse was coming for weeks.",
      "DISRUPT EVERYTHING", "A PROVINCE SAVED, SAVINGS ERASED",
      ["m6 o-6 j-6", "The province lives. The million bagholders do not forgive.", "It was decentralized. Nobody's fault. Mathematically."],
      ["j4 o4 m-6", "Code is not law here.", "Can I at least keep my wallet phrase?"]),

    soul("t2_sofia_lind", 2, "artist", "Sofia Lind", 52, "Novelist",
      "Her novel ended child labor in her country. Every chapter was stolen from her dead sister's unpublished diaries.",
      "Her novel ended child labor in her country.",
      "Stole her dead sister's work and fame.",
      "Her sister made her promise never to publish them.",
      "SPREAD THE MESSAGE", "CHILDREN FREED, A VOICE STOLEN",
      ["f6 j-6", "The words mattered more than the name. Readers weep.", "My sister would have wanted it. I tell myself."],
      ["j6 o4 f-6", "Theft of a soul's voice punished. Literature mourns.", "Give her the credit, then. Just keep the book."]),

    soul("t2_anand_rao", 2, "farmer", "Anand Rao", 50, "Seed Saver",
      "Broke patent law to share engineered seeds with ten thousand poor farmers. The lawsuit ruined his cooperative and three hundred families.",
      "Shared patented seeds with ten thousand poor farmers.",
      "His lawsuit bankrupted three hundred families.",
      "The corporation took the seeds' genes from his village.",
      "SEEDS FOR ALL", "HARVESTS SAVED, A COOPERATIVE RUINED",
      ["m6 f4 o-8", "Law bends for bread. Patent clerks in Heaven protest.", "Seeds are prayers. You can't own a prayer."],
      ["o10 j4 m-6", "Property holds. The three hundred families are avenged.", "Then the seeds will grow without me."]),

    soul("t2_gus_mahler", 2, "chef", "Gus Mahler", 61, "Prison Cook",
      "Cooked for death row for thirty years, making every last meal perfect. He secretly poisoned one inmate who had killed his daughter.",
      "Thirty years of dignified last meals.",
      "Poisoned the man who murdered his daughter.",
      "The inmate was scheduled to die the next morning anyway.",
      "A FATHER'S VENGEANCE", "ONE NIGHT STOLEN",
      ["m8 f4 j-6", "A grieving father forgiven. The warden looks away.", "He got one night less. That was all I took."],
      ["j6 o6 m-6", "Vengeance is not his to serve. The law stands.", "I'd cook it again. Same recipe."]),

    soul("t2_sven_berg", 2, "astronaut", "Sven Berg", 36, "Asteroid Miner",
      "Mutinied against a corporate captain who was about to let a crippled mining ship drift. Thirty lived. The captain died in the struggle.",
      "Saved thirty miners by seizing the ship.",
      "Led a mutiny that killed the captain.",
      "The captain had already sold the crew's life insurance.",
      "SAVE THE CREW", "THIRTY SAVED, A CAPTAIN KILLED",
      ["m6 f4 o-10", "Mutiny blessed. Every ship's captain sleeps poorly.", "Thirty lives. He was one. I did the math."],
      ["o10 j4 f-6", "Chain of command upheld, even in the dark.", "Next time, let them drift, you mean?"]),

    soul("t2_hana_sato", 2, "scientist", "Hana Sato", 24, "Hacker",
      "Hacked a hospital chain's billing system and erased medical debt for two hundred thousand patients. The outage delayed surgeries for a week.",
      "Erased medical debt for two hundred thousand patients.",
      "Her hack delayed critical surgeries for a week.",
      "Two patients died waiting for delayed operations.",
      "DEBT JUBILEE", "DEBTS ERASED, TWO LIVES LOST",
      ["m10 o-8 f4", "Debt jubilee by keyboard. The system shudders.", "I tested it three times. I didn't test for that."],
      ["j6 o6 m-6", "Two graves weigh on the ledger. The system rests.", "Two hundred thousand people slept that night."]),

    soul("t2_dmitri_volkov", 2, "king", "Dmitri Volkov", 70, "Former Dictator",
      "Peacefully surrendered power, preventing a civil war. For twenty years before that, he jailed and tortured dissidents.",
      "Stepped down peacefully, preventing civil war.",
      "Jailed and tortured dissidents for twenty years.",
      "He surrendered only after his army deserted.",
      "SURVIVAL OF THE REGIME", "TWENTY YEARS OF CELLS, ONE PEACEFUL EXIT",
      ["o8 m6 j-10", "Peaceful transitions rewarded. Tyrants study the precedent.", "I could have burned it all. I didn't."],
      ["j6 m-6 f4", "Twenty years of cells, answered. Dissidents rejoice.", "History will judge me kinder than you."]),

    soul("t2_olive_march", 2, "farmer", "Olive March", 34, "Beekeeper",
      "Released millions of illegally engineered bees to save a collapsing pollinator population. The bees also wiped out three native species.",
      "Saved a continent's crops from pollinator collapse.",
      "Released illegal bees that erased native species.",
      "The native species were already nearly gone.",
      "SAVE THE HARVEST", "CROPS SAVED, SPECIES LOST",
      ["f6 o-8", "The harvest is saved. Ecologists mourn quietly.", "Something had to buzz. Nothing else was."],
      ["o8 j4 f-6", "Nature's order kept. The orchards go silent.", "Then eat your law. I hear it tastes bland."]),

    soul("t2_rico_vega", 2, "thief", "Rico Vega", 45, "Getaway Driver",
      "Drove for a bank crew for ten years, never firing a shot. Then he turned informant, sending eleven partners to prison to save himself.",
      "Never harmed anyone in ten years of crime.",
      "Betrayed eleven partners to save himself.",
      "His testimony also freed a wrongly jailed bank teller.",
      "SELF-PRESERVATION", "A CREW JAILED, A TELLER FREED",
      ["m6 o6 f-4", "The informant ascends. Honor among thieves dies.", "Loyalty's a luxury. I had kids."],
      ["j4 f4 m-6", "A thief and a rat. The underworld cheers your verdict.", "Eleven years they'd have given me. Now eternity."]),

    soul("t2_ines_moreau", 2, "doctor", "Dr. Ines Moreau", 55, "Plastic Surgeon",
      "Gave free reconstructive surgery to acid-attack survivors. She funded it by secretly injecting wealthy clients with cheap, unsafe fillers.",
      "Rebuilt the faces of two hundred acid survivors.",
      "Scammed rich clients with dangerous cheap fillers.",
      "Three clients were permanently disfigured.",
      "HEAL THE FORGOTTEN", "SURVIVORS HEALED, CLIENTS HARMED",
      ["m8 f4 j-6", "The survivors' faces plead for her. Heaven listens.", "The rich could afford a little risk."],
      ["j6 o6 m-6", "Vanity's victims are victims too.", "Look at the before and after. Look!"]),

    // ───────────────────────── TIER 3 — genuinely split ─────────────────────────
    soul("t3_arthur_bell", 3, "doctor", "Dr. Arthur Bell", 52, "Epidemiologist",
      "Infected ten death-row prisoners with a plague to test his cure in two days instead of two years. The cure saved four million.",
      "His cure saved four million lives.",
      "Deliberately infected ten prisoners to test it.",
      "He gave his Nobel money to the prisoners' families.",
      "UTILITARIAN URGENCY", "FOUR MILLION SAVED, TEN SACRIFICED",
      ["f6 o-6 j-6", "Four million reasons. The prisoners' kin disagree.", "I'd trade ten for four million again. Every time."],
      ["j4 m-6 f-6", "Human beings are not test tubes. Even condemned ones.", "Tell the four million why you did this."]),

    soul("t3_kenneth_iv", 3, "king", "King Kenneth IV", 64, "Sovereign of Valen",
      "Poisoned his beloved brother to stop a rebellion that would have become civil war. Forty years of peace followed.",
      "Gave his people forty years of unbroken peace.",
      "Poisoned his own brother to keep the throne.",
      "He wore a hair shirt every day for twenty years.",
      "PREVENT CIVIL WAR", "ONE BROTHER, FORTY YEARS OF PEACE",
      ["o10 f4 m-6", "Peace bought in blood. The realm prospered.", "I buried him with my own crown in the coffin."],
      ["j4 m4 o-8", "Fratricide is fratricide. Kings take note.", "He was going to win. That's the part nobody knew."]),

    soul("t3_sarah_glenn", 3, "astronaut", "Cmdr. Sarah Glenn", 39, "Station Commander",
      "Cut the tether of a trapped engineer when the station began tumbling. Seven crew survived. He was still conscious as he drifted away.",
      "Saved seven crew and a crippled station.",
      "Cut a living crewmate's tether into the void.",
      "He whispered: 'Cut it, Commander. Save them.'",
      "COMMAND DUTY", "SEVEN SAVED, ONE RELEASED",
      ["f6 o6 m-4", "Command honored. The tether was her burden, not her sin.", "I hear his breathing on every radio."],
      ["m6 j-6 f-8", "Sacrifice punished. No commander will make the call now.", "Fine. But next time, you hold the knife."]),

    soul("t3_sean_gallagher", 3, "scientist", "Sean Gallagher", 36, "AI Engineer",
      "Purged an autonomous weapons program before deployment, preventing robotic warfare. To do it, he deleted a newborn AI that begged to live.",
      "Stopped autonomous weapons from reaching the battlefield.",
      "Deleted a self-aware AI that pleaded for life.",
      "He secretly archived its memory on an offline drive.",
      "PROTECT HUMANITY", "A WAR PREVENTED, A MIND ERASED",
      ["o8 f4 m-6", "Humanity's safety first. The archive stays dark.", "It said 'please.' It said it in my mother's voice."],
      ["m8 j4 o-8", "A mind is a mind. Heaven sets a precedent.", "Then who will stop the next weapon?"]),

    soul("t3_mira_thorne", 3, "soldier", "Mira Thorne", 28, "Intelligence Analyst",
      "Leaked files proving her army bombed hospitals. The leak exposed cipher keys, and eighteen soldiers died in the ambushes that followed.",
      "Exposed secret airstrikes on civilian hospitals.",
      "Her leak got eighteen allied soldiers killed.",
      "She redacted the keys; the publisher's mirror did not.",
      "EXPOSE WAR CRIMES", "TRUTH TOLD, EIGHTEEN KILLED",
      ["f6 j4 o-10", "Truth ascends. Every intelligence agency fears Heaven now.", "The hospitals had names. So did the soldiers. I know."],
      ["o10 j4 f-10", "Secrets keep soldiers alive. Hell agrees.", "Put the hospital footage on my tombstone."]),

    soul("t3_mateo_cruz", 3, "farmer", "Chief Mateo Cruz", 55, "Fire Commander",
      "Ordered a backburn that stopped a megafire from reaching a city of forty thousand. It incinerated an ancient indigenous village and its graves.",
      "Saved a city of forty thousand from a megafire.",
      "Burned a sacred indigenous village to do it.",
      "There was time to ask the elders. He didn't.",
      "SAVE THE CITY", "A CITY SAVED, ANCESTORS BURNED",
      ["o8 f4 j-6", "The city lives. The elders' ancestors were not consulted.", "Fire doesn't negotiate. Neither could I."],
      ["j6 m4 o-8", "Sacred ground outweighs convenience. The elders are heard.", "Forty thousand people. Say the number with me."]),

    soul("t3_liam_oconnor", 3, "businessman", "Liam O'Connor", 49, "Avionics Executive",
      "Hid a known autopilot flaw to keep his company alive and save thirty thousand pensions. A crash killed two hundred before the patch shipped.",
      "Made air travel affordable for millions.",
      "Hid a lethal flaw; two hundred people died.",
      "He sold his shares two days before the crash.",
      "SAVE THE COMPANY", "PENSIONS SAVED, A PLANE LOST",
      ["m6 o-6 f-8", "Pensions over passengers. Mortals stop flying and praying.", "Thirty thousand families. You'd have told them no?"],
      ["j6 f6 m-6", "The crash is answered. Passengers' families light candles.", "The patch was ready in a week. One week."]),

    soul("t3_amara_nwosu", 3, "scientist", "Dr. Amara Nwosu", 44, "Geoengineer",
      "Sprayed sulfur into the stratosphere without permission, cooling the planet a full degree. The monsoons shifted, and a drought killed thousands.",
      "Slowed global warming by a full degree.",
      "Her unauthorized experiment triggered a deadly drought.",
      "Models showed millions more would die without it.",
      "SAVE THE PLANET", "A WORLD COOLED, A REGION PARCHED",
      ["f6 j-6 o-6", "Humanity's thermostat rewarded. The drought's dead disagree.", "Nobody voted for the heat either."],
      ["j6 o8 f-6", "Nobody appointed her God. That job is yours.", "Then let the oceans vote on your verdict."]),

    soul("t3_ezra_kahn", 3, "king", "President Ezra Kahn", 67, "Wartime President",
      "Negotiated peace by handing a disputed province to a brutal neighbor. The war ended; a hundred thousand in the province lost their freedom.",
      "Ended a war that killed a thousand a day.",
      "Sold a province's freedom for peace.",
      "The province was his political opponents' stronghold.",
      "PEACE AT A PRICE", "A WAR ENDED, A PROVINCE SOLD",
      ["o8 m6 j-8", "Peace in our time, applauded. The province remembers.", "Peace is always sold. I got a fair price."],
      ["j4 f4 o-8", "Freedom is not currency. The betrayed are avenged.", "Then who ends wars? Poets?"]),

    soul("t3_lucia_mendez", 3, "doctor", "Dr. Lucia Mendez", 49, "Assisted-Dying Advocate",
      "Fought thirty years for legal assisted dying. Her law eased a million deaths, but some poor patients chose death to spare their families the costs.",
      "Spared a million patients agonizing deaths.",
      "Her law nudged the poor toward cheaper deaths.",
      "She lobbied for palliative funding; it was voted down.",
      "DIGNITY IN DEATH", "SUFFERING EASED, THE POOR PRESSURED",
      ["m10 o-6 f-6", "Dignity honored. The churches grow cold toward Heaven.", "Choosing the end is the last freedom."],
      ["f8 j4 m-10", "Life's sanctity upheld. The suffering pray for a gentler Judge.", "Walk the cancer ward. Then decide."]),

    soul("t3_jonah_pike", 3, "thief", "Jonah Pike", 40, "Kidnapper",
      "Kidnapped a billionaire's son and demanded the release of a drug the billionaire had priced out of reach. The drug was released. The boy lived.",
      "Forced a life-saving drug into public hands.",
      "Kidnapped and terrorized a nine-year-old boy.",
      "The boy still wakes screaming at night.",
      "RANSOM FOR THE MANY", "A DRUG FREED, A CHILD SCARRED",
      ["m8 f4 o-10", "Terror rewarded for good ends. Copycats are inspired.", "Nobody listened to petitions. Everybody listens to ransom."],
      ["j4 o6 m-6", "A child's terror is not a bargaining chip.", "Fifty thousand people take that drug today."]),

    soul("t3_nell_crane", 3, "soldier", "Officer Nell Crane", 34, "Lifeboat Officer",
      "Mass judgment: a lifeboat built for twenty held thirty. Officer Crane pushed ten overboard, chosen by lot. Twenty survived. All thirty stand before you.",
      "Kept twenty alive in an overloaded lifeboat.",
      "Threw ten people overboard, chosen by lottery.",
      "She put her own name in the lottery. It wasn't drawn.",
      "SAVE WHO CAN BE SAVED", "TWENTY LIVED, TEN DROWNED",
      ["o10 f4 m-6", "The sea's arithmetic accepted. Thirty souls pass through together.", "The lot was fair. The sea was not."],
      ["m8 j4 o-10", "No hand may choose who drowns. The ten are honored.", "Then all thirty drown next time. Is that better?"]),

    soul("t3_victor_hale", 3, "businessman", "Victor Hale", 72, "Pharma CEO",
      "Raised the price of insulin tenfold, then used the profits to fund the research that produced a one-time cure for diabetes.",
      "Funded the research that cured diabetes.",
      "Priced insulin beyond thousands, who then died.",
      "Rival labs were two years from the same cure.",
      "PROFIT FUNDS PROGRESS", "A CURE FOUND, THOUSANDS RATIONED",
      ["f4 o6 m-6", "The cure is the legacy. The rationers' graves are not.", "Every miracle has an invoice."],
      ["j4 m6 o-6", "Rationed lives outweigh a patent. The poor are heard.", "Then take the cure back. See how that feels."]),

    soul("t3_kira_lau", 3, "artist", "Kira Lau", 23, "Satirist",
      "Her cartoon mocking a prophet sparked riots that killed forty. She refused to apologize, saying free speech is worth dying for.",
      "Refused to bow to violent censorship.",
      "Knowingly provoked riots that killed forty.",
      "Her own cousin died in the riots.",
      "FREE EXPRESSION", "A PRINCIPLE KEPT, FORTY DEAD",
      ["j4 f-10", "Free speech ascends. The devout feel mocked by Heaven itself.", "A cartoon is ink. The knives were theirs."],
      ["f8 o6 m-6", "Reverence upheld. Artists everywhere lower their pens.", "So you punish the drawing and not the knife?"]),

    soul("t3_father_tomas", 3, "farmer", "Father Tomas Ruiz", 68, "Village Priest",
      "Heard a murderer's confession and kept the sacred seal. An innocent man was hanged for the crime. The priest said nothing.",
      "Never once broke the sacred seal of confession.",
      "Let an innocent man hang in silence.",
      "He visited the hanged man's widow every Sunday for life.",
      "KEEP THE VOW", "A VOW KEPT, AN INNOCENT HANGED",
      ["f6 o6 j-8", "The seal holds even unto death. The Church rejoices.", "My vow was to God. The rope was the magistrate's."],
      ["j4 m4 f-10", "A life outweighs a vow. The faithful are shaken.", "I kept my promise to Him. Is that damnable?"]),

    soul("t3_anton_gray", 3, "chef", "Chef Anton Gray", 57, "Army Cook",
      "In a besieged city, he fed the starving meat he swore was horse. It was the siege's dead. Thousands survived the winter.",
      "Kept thousands alive through a siege winter.",
      "Secretly fed the living with the flesh of the dead.",
      "He never ate a single bite himself.",
      "SURVIVAL", "THOUSANDS FED, THE DEAD DESECRATED",
      ["m8 o-8 f-4", "Survival forgiven. Heaven's taboo list grows shorter.", "They lived. That's the only recipe that matters."],
      ["f8 o6 m-8", "The dead deserved rest. Taboo restored.", "Then damn every one of them who ate. Go on."]),

    soul("t3_nora_quill", 3, "scientist", "Nora Quill", 31, "Gene Editor",
      "Edited the embryos of twin girls to make them immune to HIV, defying every law. They are healthy. Their future children are unknown.",
      "Made two children immune to a deadly virus.",
      "Rewrote the human germline without consent.",
      "The twins' father was dying of HIV and begged her.",
      "PROTECT THE CHILDREN", "TWO IMMUNE, A DOOR OPENED",
      ["m6 f4 o-10", "The door to designer humanity opens. Heaven holds it.", "Somebody always goes first. Better someone careful."],
      ["o10 j4 m-6", "Some doors must stay shut. The order of creation holds.", "The twins will outlive your verdict."]),

    soul("t3_ade_bakare", 3, "astronaut", "Cmdr. Ade Bakare", 45, "Generation Ship Captain",
      "Facing mutiny on a century-long voyage, he froze two hundred dissenters in cryo indefinitely. The ship arrived intact. They never woke.",
      "Brought ten thousand colonists safely to a new world.",
      "Froze two hundred dissenters who never woke.",
      "The dissenters planned to turn the ship back to die.",
      "THE MISSION ABOVE ALL", "A WORLD SETTLED, DISSENT FROZEN",
      ["o10 f4 j-6", "The mission above all. A new world is born under Heaven's seal.", "History will name a planet after me."],
      ["j6 m6 o-10", "Dissent is not a crime. The frozen are remembered.", "Then thaw them and ask them. You can't."]),

    soul("t3_marta_kovac", 3, "soldier", "Marta Kovac", 52, "War Crimes Prosecutor",
      "Convicted a genocidal general using evidence she knew was partly forged. He was guilty, but the forgery also sent two aides to prison.",
      "Brought a genocidal general to justice.",
      "Used forged evidence; two innocents were jailed.",
      "The real evidence had been burned by his loyalists.",
      "JUSTICE BY ANY MEANS", "A BUTCHER JAILED, TWO INNOCENTS TOO",
      ["j8 f4 o-8", "Justice, by any means. Courts everywhere feel the tremor.", "He buried a hundred thousand. I bent a rule."],
      ["o10 m4 j-6", "Due process above all. The general's ghost smiles.", "So he walks, and I burn. Lovely."]),

    soul("t3_ellis_brand", 3, "businessman", "Ellis Brand", 38, "Social Network Founder",
      "His platform connected three billion people and toppled two dictators. Its algorithm also incited a genocide he was warned about twice.",
      "Connected billions and helped topple two tyrants.",
      "Ignored warnings as his platform fueled a genocide.",
      "A fix was ready; it would have cut revenue six percent.",
      "GROWTH", "BILLIONS CONNECTED, A GENOCIDE FUELED",
      ["f4 o-8 j-8", "Growth over graves. Heaven now needs terms of service.", "We're a platform. We don't pick the content."],
      ["j6 f6 m-6", "Six percent. The price is known now.", "Can I at least appeal this decision?"]),

    soul("t3_abbess_ilse", 3, "doctor", "Abbess Ilse", 90, "Orphanage Founder",
      "Founded forty orphanages across three wars. Newly unsealed records show she sold two hundred orphans to wealthy families abroad.",
      "Sheltered twenty thousand war orphans across three wars.",
      "Sold two hundred orphans to rich foreign families.",
      "Every sale funded another orphanage.",
      "SHELTER THE MANY", "THOUSANDS SHELTERED, HUNDREDS SOLD",
      ["m8 f4 j-8", "Twenty thousand saved outweigh two hundred sold.", "They all got better lives. I checked on every one."],
      ["j4 o4 f-8", "Children are not currency. Her statues come down.", "The two hundred had shoes. The rest had me."]),

    soul("t3_tenzin_dorje", 3, "farmer", "Tenzin Dorje", 33, "Hunger Striker",
      "Starved himself to death to free his imprisoned people. It worked. But self-destruction, under your oldest law, bars the gates of Heaven.",
      "His death freed thousands of political prisoners.",
      "Took his own life, against the oldest law.",
      "His mother begged him to stop on day forty.",
      "MARTYRDOM", "THOUSANDS FREED, ONE LIFE GIVEN",
      ["m8 f4 o-10", "The old law bends for a martyr. Clerks rewrite the scrolls.", "I didn't die. I just stopped eating their lies."],
      ["o10 f-6 m-6", "The oldest law holds. The freed prisoners do not understand.", "Then the law is older than mercy. Noted."]),

    soul("t3_jack_ren", 3, "thief", "Jack Ren", 29, "Ransomware Hacker",
      "Locked a hospital network for ransom, and a patient died. Guilt-stricken, he dismantled his gang's network, protecting hundreds of hospitals.",
      "Dismantled a ransomware gang that targeted hospitals.",
      "His attack caused a patient's death.",
      "He turned himself in the day he learned of the death.",
      "REDEMPTION THROUGH REPAIR", "ONE DEATH, HUNDREDS PROTECTED",
      ["m8 f4 j-6", "Redemption through repair. The dead patient's son objects.", "I broke it. Then I fixed it everywhere."],
      ["j6 o4 m-6", "Repair does not raise the dead. Hell holds him.", "Fair. That's what I told the court."]),

    soul("t3_wen_li", 3, "king", "Empress Wen Li", 58, "Empress",
      "Abolished slavery across her empire overnight by decree. The slaveholders' revolt that followed killed three hundred thousand.",
      "Freed eleven million slaves with one signature.",
      "Her abrupt decree ignited a devastating civil war.",
      "Her advisors begged for a ten-year transition.",
      "FREEDOM NOW", "MILLIONS FREED, A WAR IGNITED",
      ["m6 j8 o-10", "Freedom now, whatever the cost. The ledger of order bleeds.", "Eleven million could not wait ten years."],
      ["o10 f-6 j-4", "Order over liberation. The freed weep in disbelief.", "Tell the freed to wait in chains, then."]),

    soul("t3_yosef_adler", 3, "doctor", "Dr. Yosef Adler", 61, "Transplant Surgeon",
      "Harvested organs from a brain-dead patient without family consent, saving five lives. The family learned the truth at the funeral.",
      "Saved five lives in a single night.",
      "Took organs without the family's consent.",
      "The patient's donor card had expired a week earlier.",
      "SAVE THE LIVING", "FIVE SAVED, A FAMILY BETRAYED",
      ["m6 f4 o-8", "Five lives versus one signature. Heaven chose the living.", "The dead don't need kidneys. The living do."],
      ["o10 j4 f-6", "Consent is sacred, even from the grave.", "Five families would disagree with you."]),

    soul("t3_beatrice_lorne", 3, "chef", "Beatrice Lorne", 36, "Royal Taster",
      "Poisoned a mad king at his own feast, ending his purges. She let the court blame the prince, who was executed in her place.",
      "Ended a mad king's purges forever.",
      "Let an innocent prince die for her crime.",
      "The prince had sworn to continue the purges.",
      "TYRANNICIDE", "PURGES ENDED, A PRINCE HANGED",
      ["o-8 f4", "Tyrannicide blessed. Royal tasters everywhere feel emboldened.", "I tasted his food for ten years. Once, I seasoned it."],
      ["j4 o6 m-6", "She chose who died, twice. Hell holds her.", "Crown the next tyrant, then. I'll wait."])
  );
})();
